<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUQoHUq9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUQoHUq9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUQoHUq9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUQoHUq9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUQoHUq9\App_KernelDevDebugContainer([
    'container.build_hash' => 'UQoHUq9',
    'container.build_id' => 'b2da1812',
    'container.build_time' => 1714226029,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUQoHUq9');
