<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\PageController::home'], [], [['text', '/']], [], [], []],
    'form' => [[], ['_controller' => 'App\\Controller\\PageController::form'], [], [['text', '/form']], [], [], []],
    'post' => [[], ['_controller' => 'App\\Controller\\PageController::post'], [], [['text', '/post']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\PageController::login'], [], [['text', '/login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\PageController::logout'], [], [['text', '/logout']], [], [], []],
    'App\Controller\PageController::home' => [[], ['_controller' => 'App\\Controller\\PageController::home'], [], [['text', '/']], [], [], []],
    'App\Controller\PageController::form' => [[], ['_controller' => 'App\\Controller\\PageController::form'], [], [['text', '/form']], [], [], []],
    'App\Controller\PageController::post' => [[], ['_controller' => 'App\\Controller\\PageController::post'], [], [['text', '/post']], [], [], []],
    'App\Controller\PageController::login' => [[], ['_controller' => 'App\\Controller\\PageController::login'], [], [['text', '/login']], [], [], []],
    'App\Controller\PageController::logout' => [[], ['_controller' => 'App\\Controller\\PageController::logout'], [], [['text', '/logout']], [], [], []],
];
